services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app
    ports:
      - "5432:5432"
    volumes:
      - todo_app_pgdata:/var/lib/postgresql/data

volumes:
  todo_app_pgdata:
